### ISSUE TITLE
Example using Inkwell and PositionedTapController()

### ISSUE THREAD

**Issue by IrvingArmenta-ML** [tomwyr/positioned-tap-detector#2]
I am fairly new using Flutter, but I'm looking for a way to get the position of the tap relative to an element on the view, I would like to use the `InkWell` effect on the element, therefore instead of using `GestureDetector()` I am using `InkWell()` to get the event, however, I am not sure how to get the `TapPosition` using the controller approach.

Could there be an example?

**Comment by tomwyr** [comment]
This should do the job.

```Dart
import 'package:flutter/material.dart';
import 'package:positioned_tap_detector/positioned_tap_detector.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => new MyAppState();
}

class MyAppState extends State<MyApp> {
  PositionedTapController _controller = PositionedTapController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: PositionedTapDetector(
            onTap: (it) => print(it.relative),
            controller: _controller,
            child: Material(
              color: Colors.yellow,
              child: InkWell(
                onTap: _controller.onTap,
                onTapDown: _controller.onTapDown,
                child: Container(width: 160.0, height: 160.0),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by IrvingArmenta-ML** [comment]
Great, I think for this approach there should be a `warning` about not removing or adding the `onTapDown` listener  on the children `GestureDetector()` or `InkWell()` unless is a very obvious thing, again, I'm very new using Flutter, I come from Javascript.

**Comment by tomwyr** [comment]
That's a good idea, I will update readme and make it more clear. Actually, for a second I was also confused why my example doesn't work until I realized `onTapDown` callbacks haven't been passed to detector.
